language: go
sudo: false
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/Masterminds/glide
install:
- glide install
go:
- 1.6
script:
- gocov test $(glide nv) | gocov report
notifications:
  slack:
    on_start: never
    email: false
    rooms:
      secure: CXxznZxA8pi/o4FiV2uE2PYcv/uTjpA1YKkNzHIYsc5ikEp2bbnJfaheJobGE4hXUic5EilHeTMxZG2aD28sU0WVOozcPK9HwEN/69iI1M6sTD5GJW0Z4iJM524pPSFVWU4kvl6lbROHmPqE1uWZhvpiZLbUFsGDgQVwfFc394fadeOoIZz16vSq3ycI2OnuSotyO0tZ4fn8SoQYjxhrv9rgl8IRJpOXhWgRexSeVsVzrKBZxChvtTHrr/sFpaQvNMCrqdvaK1ihXYGJrxqywy3eKUZLJ0ft7SERdkMAnXBcR3OfuOYohRe6P1Rdj4fRULjbCBXby1uEYKqb+5YSGZYkklbeHpDFnm1KM3gn/d7rS+LBtL0BL2ozBcjA7IKhf7BCJLPomHPmT3JqAVo70w4LasGOxwQJeG/WOSzwTPVFZ685AJF/fDKviqmyvEz/PF9C+giS0ntC7rKIBiyFgLSQWTwo5CErJtU+RvDuZ8LDT+nP3Jb0AGHp0EBP1F5mJjA/xxEaqPj5k2PH+zPpy7BTNDo5iinQiplytcPjsE2il0qbKNMamCSaKIGA6p99aJyo8l1mO8pjgiP0a/Z3G39ZqABFgfSzX+L5I3T60fWXznKzIegtvLTls+lPLmXljmADIT9NKXOXpmNMpbKdmr/e8MHvncBFhmFdymf/jt8=
